webserver/contest/urls.py
from django.conf.urls import patterns, url


urlpatterns = patterns('contest.views',
                       url(r'^$', 'home', name='home'),
                       # url(r'^contest/(?P<pk>\d+)/$', 'manage', name='manage'),
                       url(r'^unauthorized/$', 'unauthorized', name='403'),
                       url(r'^register/$', 'register', name='register'),
                       )

webserver/question/urls.py
from django.conf.urls import patterns, url


urlpatterns = patterns('question.views',
                       url(r'^leaderboard/$', 'leaderboard', name='leaderboard'),
                       url(r'^$', 'question_home', name='home'),
                       url(r'^(?P<qno>\d+)/$', 'question', name='question'),
                       url(r'^(?P<qno>\d+)/details/$', 'question_details', name='question_details'),
                       url(r'^language/(?P<lno>\d+)/details/$', 'language_details', name='language_details'),
                       url(r'^detail_list/', 'detail_list', name='detail_list'),
                       url(r'^attempt/(?P<att>\d+)/$', 'attempt', name='attempt'),
                       )

webserver/website/urls.py
from django.conf import settings
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.conf.urls.static import static

urlpatterns = patterns('',
                       url(r'^', include('contest.urls')),
                       url(r'^admin/', include(admin.site.urls)),
                       url(r'^question/', include('question.urls', namespace='question')),
                       url(r'^login/$', 'django.contrib.auth.views.login', {'template_name': 'login.html'}, name='login'),
                       url(r'^logout/$', 'django.contrib.auth.views.logout',
                           {'template_name': 'logged_out.html'}, name='logout'),
                       ) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

webserver/templates/401.html
{% extends 'base.html' %}
{% block body %}
{% load staticfiles %}
<h1>Error 401</h1>
<img class='img-responsive' src={% static "401.jpg" %} alt="401 meme"/>
{% endblock %}

webserver/templates/base.html
<!DOCTYPE html>
<html lang='en'>
    <head>
    <!-- Meta, title, CSS, favicons, etc. -->
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
    
    <title>-openjudge-{%block title%}{%endblock%}</title>
    <!-- Stylesheets -->
    {%load staticfiles%}
    {%load bootstrap%}
    <!-- Latest compiled and minified CSS 
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap-theme.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/js/bootstrap.min.js"></script>
    -->
    <link rel="stylesheet" href={% static 'bootstrap.min.css' %}>
    <link rel="stylesheet" href={% static 'bootstrap-theme.min.css' %}>
    <script src={% static 'jquery.min.js' %}></script>
    <script src={% static 'bootstrap.min.js' %}></script>
    {% block styles %}
    {% endblock %}
    </head>


    <body>
        <nav class='navbar navbar-default' role='navigation'>
        <div class='navbar-header'>
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navbar-collapse-1">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
        </button>
        </div><!--navbar-header-->
        <div class='collapse navbar-collapse' id='navbar-collapse-1'>
            <ul class='nav navbar-nav'>
                <li><a href={% url 'home' %}>Home</a></li>
                <li><a href={% url 'question:home' %}>Questions</a></li>
                <li><a href={% url 'register' %}>Register</a></li>
                <li><a href={% url 'question:leaderboard'%}>Leaderboard</a></li>
                {% if request.user.is_authenticated %}
                <li><a> {{user.profile}} - {{user.profile.score}}</a> </li>
                <li><a href={% url 'logout' %}>Logout</a>
                {% else %}
                <li><a> Unregistered User</a></li>
                <li> <a href={% url "login"%}>Login</a>
                {% endif %}
            </ul>
            <ul class='nav navbar-right'>
                <li> {% if contest_on %}
                    <a class='text-success'>Contest Online
                     {%else%}
                    <a class='text-danger'>Contest OffLine
                     {%endif%}
                     {{contest_time | timeuntil}} Left<br>
                     <b id='time'>{% now "jS F Y H:i"%}</b>&nbsp;</a>
                </li>
            </ul>
        </div><!-- Navbar collapse-->
        </nav>
    <div class='container text-left'>
    </div><!-- container text-left-->
    <div class='container'>
    {%block body%}
    {%endblock%}
    </div>
    <script type='text/Javascript'>
    refreshrate = 60000;
    function Clock() {
        time = document.getElementById('time');
        parts = time.innerHTML.split(' ');
        day = parts[0];
        month = parts[1];
        year = parts[2];
        clock = parts[3].split(':');
        hours = eval(clock[0]);
        minutes = eval(clock[1]);
        minutes += 1;
        if (minutes > 59){
            hours += 1;
            minutes = 0;
            if (hours > 23){
                hours = 0;
            }
        }
        clock = hours + ':' + minutes;
        time.innerHTML = day + ' ' + month + ' ' + year + ' ' +clock;
        setTimeout("Clock();", refreshrate);
    }
    setTimeout("Clock();", refreshrate);
    </script>
    </body>

</html>

webserver/templates/logged_out.html
{% extends 'base.html' %}

{% block body %}
    <p class='lead text-center' style="margin: 50px 0; font-size: 3em;">Logged out!</p>
{% endblock %}

webserver/templates/login.html
{% extends 'base.html' %}

{% block head %}
    {% load bootstrap %}
    {% load static %}
    <link rel='stylesheet' href='{% static "auth.css" %}'>
{% endblock %}

{%block body%}
<div class='container'>
<div class='col-md-4'>
    {% if form.errors %}
        <p style="color: red;">Your username and password didn't match. Please try again.</p>
    {% endif %}

    <form role='form' method="post" action="{% url 'django.contrib.auth.views.login' %}" class='form text-center'>
        {% csrf_token %}
        <h2 class="form-heading">Please Login</h2>
        {{ form | bootstrap }}
        <button class="btn btn-lg btn-success btn-block" type="submit">Login</button>
        <input type="hidden" name="next" value="{{ next }}" />
    </form>
<hr>
</div>
</div>
{%endblock%}

webserver/templates/unauthorized.html
{% extends 'base.html' %}
{% block body %}
<h1 class='bg-danger text-center'> Unauthorized</h1>
{% endblock %}