webserver/contest/urls.py
from django.conf.urls import patterns, url


urlpatterns = patterns('contest.views',
                       url(r'^$', 'home', name='home'),
                       # url(r'^contest/(?P<pk>\d+)/$', 'manage', name='manage'),
                       url(r'^unauthorized/$', 'unauthorized', name='403'),
                       url(r'^register/$', 'register', name='register'),
                       )

webserver/question/urls.py
from django.conf.urls import patterns, url


urlpatterns = patterns('question.views',
                       url(r'^leaderboard/$', 'leaderboard', name='leaderboard'),
                       url(r'^$', 'question_home', name='home'),
                       url(r'^(?P<qno>\d+)/$', 'question', name='question'),
                       url(r'^(?P<qno>\d+)/details/$', 'question_details', name='question_details'),
                       url(r'^language/(?P<lno>\d+)/details/$', 'language_details', name='language_details'),
                       url(r'^detail_list/', 'detail_list', name='detail_list'),
                       url(r'^attempt/(?P<att>\d+)/$', 'attempt', name='attempt'),
                       )

webserver/website/urls.py
from django.conf import settings
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.conf.urls.static import static

urlpatterns = patterns('',
                       url(r'^', include('contest.urls')),
                       url(r'^admin/', include(admin.site.urls)),
                       url(r'^question/', include('question.urls', namespace='question')),
                       url(r'^login/$', 'django.contrib.auth.views.login', {'template_name': 'login.html'}, name='login'),
                       url(r'^logout/$', 'django.contrib.auth.views.logout',
                           {'template_name': 'logged_out.html'}, name='logout'),
                       ) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

webserver/question/models.py
from threading import Thread
from django.core.urlresolvers import reverse
from django.db import models
from django.contrib.auth.models import User
from django.utils.timezone import now
from django.forms import ModelForm
from socket import create_connection
from contest.models import Slave
from json import loads, dumps
from queue import Queue


result_Q = Queue()

def get_alive_slaves():
    "No of slaves alive"
    slaves = Slave.objects.all()
    alive = [s for s in slaves if s.is_alive()]
    return alive


def assign_job(data, jobs={}):
    """
    Assign the job to some slave in the available list.
    """
    pk = data['pk']
    is_assigned = pk in jobs.keys()
    assignment_needed = False
    if is_assigned:
        slave = jobs[pk]
        if not slave.is_alive():
            assignment_needed = True
    else:
        assignment_needed = True

    if assignment_needed:
        slaves = get_alive_slaves()
        # if slaves: what if there are no slaves?
        assigned = False
        while not assigned:  # assign to first non busy slave
            for slave in slaves:
                if not slave.busy:
                    jobs[pk] = slave
                    assigned = True
    address = jobs[pk].get_address()
    return jobs[pk], address

def ask_check_server(data):
    """
    Ask the check server is the current attempt done?
    Returns None/True/False and comments.
    data is of type
        data = {
            'pk'        :primary key of attempt,
            'qno'       :question number pk,
            'source'    :source code,
            'name'      :name of file,
            'language'  :language pk,
            }
    """
    slave, address = assign_job(data)

    with slave:
        try:
            sock = create_connection(address)
        except:
            value, remarks = None, 'Connection error'
        else:
            data = dumps(data)
            sock.sendall(data.encode('utf-8'))
            resp = sock.recv(4096)
            resp, remarks = loads(resp.decode())
        finally:
            sock.close()

    if resp == 'Timeout':
        value, remarks = False, resp
    elif resp == 'Correct':
        value, remarks = True, resp
    elif resp == 'Incorrect':
        value, remarks = False, resp
    elif resp == 'Error':
        value, remarks = False, remarks
    global result_Q
    data = loads(data)
    result_Q.put((data['pk'], value, remarks))


class Profile(User):
    """
    A user profile.
    Stores scores and other data
    """
    last_solved = models.DateTimeField(default=now)

    def _get_score(self):
        "Get the user's current score"
        attempts = Attempt.objects.filter(player=self).filter(correct=True)
        score = attempts.aggregate(models.Sum('marks'))
        print(score, 'score')
        marks = score['marks__sum']
        return marks if marks is not None else 0
    score = property(_get_score)


class Language(models.Model):
    """A programming language which is available on the check server.
    """
    def __str__(self):
        return self.name
    name = models.CharField(max_length=100)
    details = models.TextField()
    wrapper = models.FileField(upload_to='wrappers')
    overwrite = models.BooleanField(default=False,
                                    help_text='overwrite required\
                                    for storing the source code')


class Attempt(models.Model):
    """An attempt on a question"""
    def __str__(self):
        return self.question.__str__() + ' - ' + self.player.__str__()
    player = models.ForeignKey('Profile', related_name='player')
    question = models.ForeignKey('Question', related_name='question')
    language = models.ForeignKey('Language', related_name='language')
    source = models.TextField(null=True)
    source_name = models.CharField(max_length=30,
                                   help_text='Name of source code file',
                                   null=True)
    correct = models.NullBooleanField(default=None)
    stamp = models.DateTimeField(auto_now_add=True)
    marks = models.FloatField()
    remarks = models.TextField()  # Remarks from the check server go there

    def get_absolute_url(self):
        "Get the absolute url of the attempt"
        return reverse('question:attempt', kwargs={'att': self.pk})

    def get_json__(self):
        """
        Return essential data as dict
        """
        data = {'pk': self.pk,
                'qno': self.question.pk,
                'source': self.source,
                'name': self.source_name,
                'language': self.language.pk,
                }
        return data

    def is_correct(self):
        """Checks if the attempt was correct
        By contacting the check server."""
        if self.correct is not None:
            return self.correct
        else:
            data = self.get_json__()
            t = Thread(target=ask_check_server, args=(data,))
            t.start()
            global result_Q
            results = {}
            while result_Q.qsize() > 0:
                key, val, rem = result_Q.get()
                results[key] = (val, rem)
            pk = data['pk']
            result, comment = None, "Checking..."
            for key, value in results.items():
                if key == pk:
                    result, comment = value
                else:
                    result_Q.put((key, value[0], value[1]))
            self.correct = result
            self.remarks = comment
            self.marks = self.question.get_marks()
            self.save()
            return self.correct


class Question(models.Model):
    """A question in the competition"""
    qno = models.IntegerField()
    title = models.CharField(max_length=50)
    text = models.TextField(default='Question text goes here')
    practice = models.BooleanField(default=False)
    # -----------

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('question:question', kwargs={'qno': self.qno})

    def has_been_answered(self, user):
        attempts = Attempt.objects.filter(question=self, player=user.profile)
        # assume that not attempted
        answered = False
        for att in attempts:
            res = att.is_correct()
            # is any one of them pending checks?
            if ((res is None) or
                (res is True)):
                    answered = True
                    break
        return answered


    def get_marks(self):
        """Get the current score for a question"""
        if self.practice:
            return 0
        total_attempts = Attempt.objects.filter(
            question=self).exclude(correct=None).count()
        if total_attempts == 0:
            score = 1.0
        else:
            wrong_attempts = Attempt.objects.filter(
                question=self, correct=False).count()
            score = float(wrong_attempts) / float(total_attempts)
        return score

class AnswerType(models.Model):
    """Used to determine which type of checking to use.
    Error tolerant or exact.
    For future use."""

    def __str__(self):
        return self.name
    name = models.CharField(max_length=50)


class Answer(models.Model):
    """The answer to a question"""
    def __str__(self):
        return self.question.__str__()
    question = models.OneToOneField(Question)
    infile = models.FileField(upload_to='test_cases')
    outfile = models.FileField(upload_to='test_cases')
    sample_code = models.FileField(upload_to='solutions')
    answer_type = models.ForeignKey(AnswerType, related_name='answer_type')


class AttemptForm(ModelForm):
    class Meta:
        model = Attempt
        exclude = ['player', 'question', 'stamp',
                   'correct', 'marks', 'remarks']

webserver/question/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth.decorators import login_required
from question import models
from django.http import JsonResponse
from question import functions
from contest.functions import is_contest_on


def leaderboard(request):
    """The scoreboard"""
    data = {}
    template = 'question/leaderboard.html'
    players = list(models.Profile.objects.all())
    players.sort(key=lambda p:p.score, reverse=True)
    data['players'] = players
    data['questions'] = models.Question.objects.order_by('qno')
    return render(request, template, data)


def question_home(request):
    """Show all questions"""
    data = {}
    template = 'question/question.html'
    data['questions'] = models.Question.objects.all()
    return render(request, template, data)


@login_required
def question(request, qno):
    """Display a question and the form to accept the user's answer"""
    qno = int(qno)
    data = {}
    template = 'question/question.html'
    ques = get_object_or_404(models.Question, qno=qno)
    if (is_contest_on() or ques.practice):
        data['question'] = ques
        data['marks'] = data['question'].get_marks()
        data['attempts'] = models.Attempt.\
            objects.filter(question=data['question'],
                           player=request.user.profile).order_by('-stamp')
        if len(data['attempts']) > 0:
            last_correct = data['attempts'][0].correct
        else:
            last_correct = False
        data['last_correct'] = last_correct

        if not ques.has_been_answered(request.user):
            # Only if the question is yet to be answered, say yes
            if request.method == 'GET':
                data['answer_form'] = functions.get_attempt_form(
                    ques, request.user.profile)
            if request.method == 'POST':
                data['answer_form'] = models.AttemptForm(
                    request.POST, request.FILES)
                if data['answer_form'].is_valid():
                    form = data['answer_form']
                    attempt = form.save(commit=False)
                    attempt.player = request.user.profile
                    attempt.question = data['question']
                    attempt.marks = data['marks']
                    attempt.save()
                    if attempt.is_correct():  # force a check request
                        functions.update_marks(request.user.profile, attempt)
                    return redirect('question:question', qno=qno)

    return render(request, template, data)


def question_details(request, qno):
    """
    Details pertaining to a question to be used by the
    Check server
    """
    data = {}
    qno = int(qno)
    question = get_object_or_404(models.Question, qno=qno)
    #  -----
    data['inp'] = question.answer.infile.url
    data['out'] = question.answer.outfile.url
    data['type'] = question.answer.answer_type.pk
    return JsonResponse(data)


def attempt(request, att):
    data, att = {}, int(att)
    template = 'question/attempt.html'
    # -----
    attempt = get_object_or_404(models.Attempt, pk=att)
    data['attempt'] = attempt
    attempt.is_correct()
    return render(request, template, data)


def language_details(request, lno):
    """
    Language details to be use by the Check server
    """
    data = {}
    lno = int(lno)
    language = get_object_or_404(models.Language, lno=lno)
    # -----
    data['wrap'] = language.wrapper.url
    data['misc'] = language.details
    return JsonResponse(data)


def detail_list(request):
    """
    A JSON containing all details pertaining to all questions
    and languages on the server
    """
    data = {}
    questions = models.Question.objects.all()
    data['question'] = {}
    for q in questions:
        data['question'][str(q.pk)] = {'inp': q.answer.infile.url,
                                       'out': q.answer.outfile.url,
                                       'type': q.answer.answer_type.pk
                                       }
    languages = models.Language.objects.all()
    data['language'] = {}
    for l in languages:
        data['language'][str(l.pk)] = {'wrap': l.wrapper.url,
                                       'misc': l.details,
                                       'overwrite': l.overwrite
                                       }
    return JsonResponse(data)

webserver/question/templates/question/attempt.html
{%extends 'base.html'%}
{%block title%}Attempt {{attempt.pk}}{%endblock%}

{%block body%}
    <div class='container text-left'>
        <p class='lead'>{{attempt.pk}}</p>
        <div class='table-responsive'>
            <table class='table table-hover'>
                <thead><tr>
                    <th>Language</th>
                    <th>Source Name</th>
                    <th>Marks</th>
                    <th>Question</th>
                    <th>Time-Stamp</th>
                    <th>Is Correct</th>
                </tr></thead>
                <tbody>
                        <tr>
                            <td>{{attempt.language}}</td>
                            <td>{{attempt.source_name}}</td>
                            <td>{{attempt.marks}}</td>
                            <td>{{attempt.question}}</td>
                            <td>{{attempt.stamp}}</td>
                            <td>{{attempt.correct}}</td>
                        </tr>
                </tbody>
            </table>
            <hr>
            <h3>Source Code</h3>
            <pre>{{attempt.source}}</pre>
            <h3>Remarks</h3>
            <pre>{{attempt.remarks}}</pre>
        </div>
        </div>
    </div>
{%endblock%}

webserver/question/templates/question/leaderboard.html
{%extends 'base.html'%}
{%block title%}LeaderBoard{%endblock%}

{%block body%}
<div class='table-responsive'>
    <table class='table table-hover table-striped'>
        <thead><tr>
            <th>Rank</th>
            <th>Player</th>
            <th>Score</th>
            <th>LastSolve</th>
        </tr></thead>
        <tbody>
            {%for p in players%}
                <tr>
                    <td>{{forloop.counter}}</td>
                    <td>{{p}}</td>
                    <td>{{p.score}}</td>
                    <td>{{p.last_solved|timesince}}</td>
                </tr>
            {%endfor%}
        </tbody>
    </table>
</div>
<script type="text/JavaScript">
<!--
function timedRefresh(timeoutPeriod) {
    setTimeout("location.reload(true);",timeoutPeriod);
}
timedRefresh(10000);
//   -->
</script>
{%endblock%}

webserver/question/templates/question/question.html
{%extends 'base.html'%}
{%block title%}Question {{question.qno}}{%endblock%}
{% block styles %}
<style type="text/css" media="screen">
    #temp_text_area { 
    width: 100%;
    height: 500px;
    }
</style>
<script>
function check(pk){
$.ajax({url: '/question/attempt/' + pk;,
    success: function(result){
        if(result.indexOf('Checking...') != -1){
            setTimeout(check(pk), 500);
        }
        else
        {
            document.location.reload();
        }
    }});
            }
</script>
{% endblock %}

{%block body%}
    <div class='container text-left'>
        {% if questions %}{# if it is a list of questions #}
            <div class='row'>
                <h3 class='text-primary'>Questions</h3>
                <b>Questions in green are practice questions and carry no marks.</b>
            </div>

            <ol class='col-md-5'>
                {% for ques in questions %}
                    <li class='bg-{% if ques.practice %}success
                                  {% else %}danger
                                  {% endif %}'>
                    <a href={{ ques.get_absolute_url }}>{{ques.title}}</a></li>
                {% endfor %}
            </ol>
        {% elif question %}{# if it is an individual question #}
        {% if last_correct %}{# correct answer recieved #}
            <div class="alert alert-success alert-dismissible" role="alert">
                Correct Answer. Further attempts on this question will be ignored.
                {% else %}{# something went wrong #}
            <div class="alert alert-danger alert-dismissible" role="alert">
                If you are seeing this one of the following is true:
                <ul>
                    <li>This is your first time on this question. If so <strong>ignore this message</strong></li>
                    <li>Your last attempt was wrong(See Attempt History Tab)</li>
                    <li>Your last attempt had errors(See Attempt History Tab)</li>
                </ul>
        {% endif %}
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
        {# TABS for QUESTION #}
            <ul class="nav nav-tabs">
                <li role="presentation" class="active"><a data-toggle="tab" href="#question_attempt">Question</a></li>
                <li role="presentation"><a data-toggle="tab" href="#attempt_form">Code Editor</a></li>
                <li role="presentation"><a data-toggle="tab" href="#attempt_history">Attempt History</a></li>
            </ul>
            <div class="tab-content">
                <div class="tab-pane fade in active" id="question_attempt">
                    <p class='lead'>{{question.qno}}: {{question.title}}</p>
                    <p class='bg-warning'>Marks on page load: {{marks}}</p>
                    <pre>{{question.text}}</pre>
                    <hr>
                </div>
                {% if answer_form %}
                <div class='tab-pane fade' id='attempt_form'>
                    <form role='form' action={%url "question:question" question.qno %} method='post'>
                        {%csrf_token%}
                        {%load bootstrap%}
                        {{answer_form|bootstrap}}
                        <div class='well'>
                            <div id="temp_text_area">
                            </div>
                        </div>
                        <input type='submit' class='btn btn-success' value='Submit'></input>
                    </form>
                </div>
                {% endif %}
                <div class="tab-pane fade" id="attempt_history">
                    <div class='table-responsive'>
                        <table class='table table-hover'>
                            <thead><tr>
                                <th>Attempt Details</th>
                                <th>Time-Stamp</th>
                                <th>Marks</th>
                                <th>Remarks</th>
                            </tr></thead>
                            <tbody>
                                {%for a in attempts%}
                                    <tr>
                                        <td><a href={{a.get_absolute_url}}> See attempt no {{a.pk}}</a></td>
                                        <td>{{a.stamp}}</td>
                                        <td>{{a.marks}}</td>
                                        <td><pre>{{a.remarks}}</pre></td>
                                    </tr>
                                {%endfor%}
                            </tbody>
                        </table>
                </div>
        </div>
        {% endif %}
    </div>
    {% load staticfiles %}
    <script src="{% static 'ace/ace.js' %}" type="text/javascript" charset="utf-8"></script>
    <script src="{% static 'ace/ext-modelist.js' %}" type="text/javascript" charset="utf-8"></script>
    <script>
        var editor = ace.edit("temp_text_area");
        var textarea = $('textarea[id="id_source"]');
        var label = $('label[for="id_source"]').hide(); textarea.hide();

        editor.getSession().setValue(textarea.val());
        editor.getSession().on('change', function(){
      textarea.val(editor.getSession().getValue());
        });
        editor.setTheme("ace/theme/monokai");

        var source_name = $('input[id="id_source_name"]');
        function new_mode() {
            var source_name = $('input[id="id_source_name"]');
            var filePath = source_name.val();
            var modelist = ace.require("ace/ext/modelist");
            var mode = modelist.getModeForPath(filePath).mode
            editor.session.setMode(mode)
        }
        new_mode()
        source_name.change(new_mode)
        editor.setFontSize(18);
    </script>
    {% for a in attempts %}
        {% if a.remarks == 'Checking...' %}
        <script> check({{a.pk}}); </script>
        {% endif %}
    {% endfor %}
{%endblock%}